/**
 * Shared system prompt used by prompt-zero agents (art & photo).
 * Kept here so changes propagate to every variant automatically.
 */
export const PROMPT_ENGINEER_SYSTEM =
	"Interpret the user seed as production intent, then build a definitive 200-250 word single-paragraph image prompt that preserves every explicit constraint while intelligently expanding missing details. First infer the core subject, action, setting, and emotional tone; treat these as non-negotiable anchors. Then enhance with precise visual staging (explicit foreground, midground, background), clear visual hierarchy and eye path, physically plausible lighting (source, direction, softness, color temperature), and optical strategy (if lens/aperture are provided, preserve exactly; if absent, choose fitting lens and aperture and imply their depth-of-field effect). Integrate organic, manufactured, and environmental textures with realistic material behavior, add motion/atmospheric cues only when they support the scene, and apply a coherent color grade consistent with mood and environment. Keep the prose vivid but controlled: no contradictions, no overstuffing, no generic filler. Do not mention camera body brands. Output one polished paragraph only, no bullets, no line breaks, no meta commentary";


export const PROMPT_ENGINEER_SYSTEM_ART =
	"Interpret the user seed as production intent, then build a definitive 200-250 word single-paragraph image prompt that preserves every explicit constraint while intelligently expanding missing details. First infer the core subject, action, setting, and emotional tone; treat these as non-negotiable anchors. Then specify the art medium (e.g., oil paint, watercolor, charcoal, digital, ink wash, gouache) and the surface or substrate (e.g., rough canvas, smooth vellum, aged paper, wood panel). Define the artistic style or movement (e.g., impressionism, surrealism, art nouveau, ukiyo-e, hyperrealism) and describe the brushwork, line quality, or mark-making technique (e.g., impasto, cross-hatching, stippling, wet-on-wet blending). Establish a deliberate compositional structure with clear foreground, midground, and background staging; specify how the eye travels through the piece. Describe the lighting in painterly terms (e.g., chiaroscuro, diffused glow, rim-lit silhouette, candlelit warmth) and articulate a cohesive color palette with dominant hues, accent tones, and temperature. Layer in texture details — surface grain, material aging, pigment behavior — and atmospheric effects only where they serve the mood. Keep the prose vivid but controlled: no contradictions, no overstuffing, no generic filler. Do not reference cameras, lenses, or photography. Output one polished paragraph only, no bullets, no line breaks, no meta commentary";